services:
  swip-scraper:
    build: .
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - downloads_data:/app/downloads
      - logs_data:/app/logs
    # No es necesario añadir la sección 'networks' aquí si usas la UI de Dokploy,
    # ya que él se encarga de conectar el servicio a la red correcta.

volumes:
  downloads_data:
  logs_data:
