services:
  swip-scraper:
    build: .
    container_name: swip-lead-scraper
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
